### ISSUE TITLE
Add "prior art" section (or similar)

### ISSUE THREAD

**Issue by miketaylr** [explainers-by-googlers/HSTS-Tracking-Prevention#2]
We should add a section to the explainer that covers some of the prior thinking, including https://github.com/mikewest/strict-navigation-security as well as what Safari and Firefox have launched or blogged about before.

**Comment by miketaylr** [comment]
> as what Safari and Firefox have launched or blogged about before.

Or anyone else for that matter!

**Comment by sbingler** [comment]
Sounds good, I'll gather some references to add. If anyone have a good suggestion feel free to mention it here.

**Comment by tomayac** [comment]
@johnwilander from Apple pointed at [WebKit's blog post](https://webkit.org/blog/8146/protecting-against-hsts-abuse/) on their approach.
